### ISSUE TITLE
KeyError: 'Block'

### ISSUE THREAD

**Issue by rickymac68** [Kodex-Data-Systems/Casper#30]
Hi,
   I ran Casper option 21) Fork Check on Friday mid-day and it returned the number 100. Later in the day my node was selected for 2 leadership spots in Epoch 8. Then my node went to produce blocks at the appointed time and did not return the results in time. I will attach the janalyze screen shot. Here is the error
(
<img width="1486" alt="Screen Shot 2019-11-15 at 9 13 37 PM" src="https://user-images.githubusercontent.com/25856278/68988582-8ef12280-07ee-11ea-99ef-2b62c5daa24e.png">
21) Fork Check

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./__main__.py", line 382, in <module>
    cliui.run()
  File "./__main__.py", line 321, in run
    analyze.forkcheck()
  File "./janalyze/__init__.py", line 91, in forkcheck
    if(thisblockhex == result['status']['Block']['block']):
KeyError: 'Block'

Versions my node is running: Casper (v) Show versions
STARTING CASPER CORE v0.0.4
OS Darwin-19.0.0-x86_64-i386-64bit
jcli 0.7.0 (HEAD-a93d4f67, release, macos [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
jormungandr 0.7.0 (HEAD-a93d4f67, release, macos [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
Python 3.7.5

**Comment by oldcryptogeek** [comment]
https://github.com/Kodex-Data-Systems/Casper/pull/32
