### ISSUE TITLE
Checking message log can crash Casper

### ISSUE THREAD

**Issue by Scitz0** [Kodex-Data-Systems/Casper#35]
If message log is empty and you choose to check message log in Casper it will crash with below Traceback.

A check needs to be added before "header = message_logs[0].keys()" that checks if message_logs is empty and if so gracefully give a message about this else print according to existing code.

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./__main__.py", line 385, in <module>
    cliui.run()
  File "./__main__.py", line 241, in run
    header = message_logs[0].keys()
IndexError: list index out of range

**Comment by oldcryptogeek** [comment]
#37
