### ISSUE TITLE
Bug Fernet - Import new Address then Load Addresses

### ISSUE THREAD

**Issue by benjehan** [Kodex-Data-Systems/Casper#6]
Traceback (most recent call last):
  File "caspercli.py", line 268, in <module>
    cliui.run()
  File "caspercli.py", line 89, in run
    myaccounts = casper.db.all_acct()
  File "/Users/Ben/Casper/casper/database.py", line 121, in all_acct
    return self._decrypt_rows(encrypted_rows)
  File "/Users/Ben/Casper/casper/database.py", line 56, in _decrypt_rows
    _acct_public = self.cipher.decrypt(row[3])
  File "/Users/Ben/Casper/casper/fernet.py", line 37, in decrypt
    return self.f.decrypt(token).decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 69: ordinal not in range(128)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by oldcryptogeek** [comment]
@benjehan https://github.com/Kodex-Data-Systems/Casper/pull/10

**Comment by oldcryptogeek** [comment]
Traceback (most recent call last):
  File "__main__.py", line 303, in <module>
    print (9 * " \U0001f47b ")
UnicodeEncodeError: 'ascii' codec can't encode character '\U0001f47b' in position 1: ordinal not in range(128)

**Comment by oldcryptogeek** [comment]
https://github.com/Kodex-Data-Systems/Casper/commit/d0359464045e919fd4b56449e8310f91d21f8900
